### ISSUE TITLE
Major log spam

### ISSUE THREAD

**Issue by ryleu** [fzzyhmstrs/EMI_loot#9] opened 2023-01-22 03:26 UTC
![image](https://user-images.githubusercontent.com/69326171/213899162-9e1c4570-6dd2-4abe-b33a-0473ef3447fd.png)

Stupid amount of log spam when used with repurposed structures, byg, frostiful, or pretty much any other mod that adds loot chest tables.

**Comment by fzzyhmstrs** [comment] 2023-01-27 13:44
For some reason the recipes are getting sent twice. What versions of EMI, EMI Loot,are you using? My test world doesn't have any duplicated recipes and has mods that add chest loot.

**Comment by Fauli1221** [comment] 2023-02-04 21:37
I have the same issue with emi-loot 0.5.0+1.19

**Comment by fzzyhmstrs** [comment] 2023-02-04 21:43
> I have the same issue with emi-loot 0.5.0+1.19

Can you send me one of these logs please? I'll try to see if I can replicate and diagnose

**Comment by fzzyhmstrs** [comment] 2023-02-04 21:46
And can you see if the log spam persists for you after updating to the most recent version? (0.6.0)

**Comment by Fauli1221** [comment] 2023-02-04 22:06
> > I have the same issue with emi-loot 0.5.0+1.19

> Can you attach one of these logs here please? I'll try to see if I can replicate and diagnose

I'm currently playing to see if I can reproduce it since it seems to be related to EMI reloads, but here is a recent log from one of my modpack players who encountered the log spam he had a crash at the end which is unrelated to this, that's why he sent it to me:
https://mclo.gs/DpXYUrA

I will send my own log once I get it the first time on this pc

**Comment by Fauli1221** [comment] 2023-02-04 22:08
> And can you see if the log spam persists for you after updating to the most recent version? (0.6.0)

I will update the modpack to 0.6.0 today and will check if I encounter it again

**Comment by Fauli1221** [comment] 2023-02-05 19:48
here I have a log with the issue on 0.6.0:

https://mclo.gs/UMsZA2I

**Comment by fzzyhmstrs** [comment] 2023-02-05 19:54
> here I have a log with the issue on 0.6.0:
> 
> https://mclo.gs/UMsZA2I

Hm... That's every single recipe being duplicated somehow. You got this to happen on your instance? If so so, can you please turn on debug mode and replciate again? In the EmiLootConfig json in the config folder. The log spam will get _a lot_ worse, but hopefully it'll show something useful

**Comment by Fauli1221** [comment] 2023-02-10 20:30
got a log that had the issue with debug mode on: 
https://mclo.gs/Udsg74s

Ignore the crash at the end that's a Xorg issue

sorry that I took so long, didn't have the time to play

**Comment by fzzyhmstrs** [comment] 2023-02-10 20:51
Alright, that is just the insight I needed. It looks like you connected and disconnected from the server/world twice, and each time it is synchronizing loot tables, which is correct. What isn't correct, at first glance, is EMI Loot isn't properly clearing the synced data after disconnecting

**Comment by fzzyhmstrs** [comment] 2023-02-18 19:09
Fixed in 0.6.1

**Closed by fzzyhmstrs** 2023-02-18 19:09 UTC
