### ISSUE TITLE
mod can't be load

### ISSUE THREAD

**Issue by bucketBrian** [fzzyhmstrs/EMI_loot#80] opened 2024-09-14 01:54 UTC
![image](https://github.com/user-attachments/assets/5d9aa79b-8df4-4be5-bab4-bf59485cecb2)
[crash-2024-09-13_21.49.08-fml.txt](https://github.com/user-attachments/files/17000490/crash-2024-09-13_21.49.08-fml.txt)
[latest.log](https://github.com/user-attachments/files/17000493/latest.log)

This only happens with the versions above 0.6, I tried 0.6.6 and it's loaded properly.

**Comment by fzzyhmstrs** [comment] 2024-09-14 03:24
Hello, this was caused by a mistake with Fzzy Config 0.4.2. Please update to the new Fzzy Config 0.4.3 and the error should be fixed.

**Closed by fzzyhmstrs** 2024-09-14 03:24 UTC

**Comment by bucketBrian** [comment] 2024-09-14 03:29
That‘s quite fast...
Did you just updated it for this one specially?

**Comment by fzzyhmstrs** [comment] 2024-09-14 03:33
Yes, I just updated. The mistake broke loading for all Minecraft versions so a fix was really needed.
